
package ing_soft;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.*;

public class interfaz_principal extends javax.swing.JFrame implements Runnable{
    
    String hora, minutos, segundos, ampm;
    Calendar calendario;
    Thread h1; 


    /**
     * Creates new form interfaz_principal
     */
    public interfaz_principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        jpanel_opc_nuevo_grupo.setVisible(false);
        panel_agregar_alumnos.setVisible(false);
        jpanel_opc_buscar_grupo.setVisible(true);
        jpanel_clase.setVisible(false);
        panel_tomar_asistencia_alumno.setVisible(false);
        Guarda_Hora_inicial_de_clase.setVisible(false);
        
        h1 = new Thread(this);
        h1.start();

        
        
        ObtenerGrupos();
        ReiniciarTabla();
        mostrarFecha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        Panel_Principal = new javax.swing.JPanel();
        panel_conenedor_superior = new javax.swing.JPanel();
        Panel_boton_ayudante = new javax.swing.JPanel();
        bnt_mod_ayud = new javax.swing.JButton();
        Panel_etiqueta_FECHA = new javax.swing.JPanel();
        lbl_fecha = new javax.swing.JLabel();
        Panel_etiqueta_HORA = new javax.swing.JPanel();
        lbl_hora = new javax.swing.JLabel();
        panel_contenedor_botones = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        select_grupos = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btn_nuevo_grupo = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btn_inicar_clase = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        bnt_importar_datos = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        tbn_generar_archivo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jpanel_opc_buscar_grupo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla_datos_grupos = new javax.swing.JTable();
        jlb_grupo_seleccionado = new javax.swing.JLabel();
        btn_editar_grupo = new javax.swing.JButton();
        btn_elimimnar_grupo = new javax.swing.JButton();
        jbl_set_nom_gupo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbl_set_nom_prof = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbl_set_nom_Materia = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jpanel_opc_nuevo_grupo = new javax.swing.JPanel();
        lbl_nom_prof = new javax.swing.JLabel();
        lbl_nom_grupo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtf_nom_grupo = new javax.swing.JTextField();
        jtf_nom_prof = new javax.swing.JTextField();
        jtf_ciclo = new javax.swing.JTextField();
        lbl_materia = new javax.swing.JLabel();
        jtf_materia = new javax.swing.JTextField();
        lbl_warnigs = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_crear_grupo = new javax.swing.JButton();
        btn_actualizar_grupo = new javax.swing.JButton();
        panel_agregar_alumnos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtf_input_nomalum = new javax.swing.JTextField();
        jtf_input_boletaalum = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jpanel_clase = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panel_tomar_asistencia_alumno = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtf_input_asistencia_nomalum_ = new javax.swing.JTextField();
        jtf_input_asistencia_boletaalum = new javax.swing.JTextField();
        btn_tomar_asistencia_alum = new javax.swing.JButton();
        Guarda_Hora_inicial_de_clase = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Principal.setBackground(new java.awt.Color(204, 255, 255));

        panel_conenedor_superior.setLayout(new java.awt.GridBagLayout());

        Panel_boton_ayudante.setBackground(new java.awt.Color(204, 204, 255));
        Panel_boton_ayudante.setLayout(new java.awt.GridBagLayout());

        bnt_mod_ayud.setText("Modo Ayudante");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 84, 35, 106);
        Panel_boton_ayudante.add(bnt_mod_ayud, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        panel_conenedor_superior.add(Panel_boton_ayudante, gridBagConstraints);

        Panel_etiqueta_FECHA.setBackground(new java.awt.Color(204, 204, 255));
        Panel_etiqueta_FECHA.setLayout(new java.awt.GridBagLayout());

        lbl_fecha.setText("FECHA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 124, 36, 145);
        Panel_etiqueta_FECHA.add(lbl_fecha, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        panel_conenedor_superior.add(Panel_etiqueta_FECHA, gridBagConstraints);

        Panel_etiqueta_HORA.setBackground(new java.awt.Color(204, 204, 255));
        Panel_etiqueta_HORA.setLayout(new java.awt.GridBagLayout());

        lbl_hora.setText("HORA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 121, 34, 148);
        Panel_etiqueta_HORA.add(lbl_hora, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 24);
        panel_conenedor_superior.add(Panel_etiqueta_HORA, gridBagConstraints);

        panel_contenedor_botones.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        panel_contenedor_botones.add(jPanel3);

        select_grupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_gruposActionPerformed(evt);
            }
        });
        panel_contenedor_botones.add(select_grupos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        panel_contenedor_botones.add(jPanel1);

        btn_nuevo_grupo.setText("NuevoGrupo");
        btn_nuevo_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevo_grupoActionPerformed(evt);
            }
        });
        panel_contenedor_botones.add(btn_nuevo_grupo);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        panel_contenedor_botones.add(jPanel8);

        btn_inicar_clase.setText("Iniciar clase");
        btn_inicar_clase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicar_claseActionPerformed(evt);
            }
        });
        panel_contenedor_botones.add(btn_inicar_clase);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        panel_contenedor_botones.add(jPanel9);

        bnt_importar_datos.setText("Asistencia");
        panel_contenedor_botones.add(bnt_importar_datos);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        panel_contenedor_botones.add(jPanel10);

        tbn_generar_archivo.setText("Importar");
        panel_contenedor_botones.add(tbn_generar_archivo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        panel_contenedor_botones.add(jPanel2);

        jtabla_datos_grupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtabla_datos_grupos);

        jlb_grupo_seleccionado.setText("Grupo: ");

        btn_editar_grupo.setText("Editar");
        btn_editar_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar_grupoActionPerformed(evt);
            }
        });

        btn_elimimnar_grupo.setText("Eliminar");

        jbl_set_nom_gupo.setText("NOMGRUP");

        jLabel2.setText("Profesor:");

        jbl_set_nom_prof.setText("Nom_Prof");

        jLabel3.setText("Materia:");

        jbl_set_nom_Materia.setText("Nom_materia");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agregar Alumnos", "Manual", "QR" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_opc_buscar_grupoLayout = new javax.swing.GroupLayout(jpanel_opc_buscar_grupo);
        jpanel_opc_buscar_grupo.setLayout(jpanel_opc_buscar_grupoLayout);
        jpanel_opc_buscar_grupoLayout.setHorizontalGroup(
            jpanel_opc_buscar_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_opc_buscar_grupoLayout.createSequentialGroup()
                .addGroup(jpanel_opc_buscar_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_opc_buscar_grupoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpanel_opc_buscar_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jpanel_opc_buscar_grupoLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jlb_grupo_seleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbl_set_nom_gupo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbl_set_nom_prof, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbl_set_nom_Materia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jpanel_opc_buscar_grupoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btn_editar_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_elimimnar_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpanel_opc_buscar_grupoLayout.setVerticalGroup(
            jpanel_opc_buscar_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_opc_buscar_grupoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_opc_buscar_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_grupo_seleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbl_set_nom_gupo)
                    .addComponent(jLabel2)
                    .addComponent(jbl_set_nom_prof)
                    .addComponent(jLabel3)
                    .addComponent(jbl_set_nom_Materia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_opc_buscar_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_editar_grupo)
                    .addComponent(btn_elimimnar_grupo)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        lbl_nom_prof.setText("Nombre del profesor:");

        lbl_nom_grupo.setText("Nombre del grupo:");

        jLabel1.setText("Ciclo escolar:");

        lbl_materia.setText("Materia:");

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        btn_crear_grupo.setText("Aceptar");
        btn_crear_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crear_grupoActionPerformed(evt);
            }
        });
        jPanel4.add(btn_crear_grupo);

        btn_actualizar_grupo.setText("Actualizar");
        btn_actualizar_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_grupoActionPerformed(evt);
            }
        });
        jPanel4.add(btn_actualizar_grupo);

        javax.swing.GroupLayout jpanel_opc_nuevo_grupoLayout = new javax.swing.GroupLayout(jpanel_opc_nuevo_grupo);
        jpanel_opc_nuevo_grupo.setLayout(jpanel_opc_nuevo_grupoLayout);
        jpanel_opc_nuevo_grupoLayout.setHorizontalGroup(
            jpanel_opc_nuevo_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_opc_nuevo_grupoLayout.createSequentialGroup()
                .addGap(434, 434, 434)
                .addGroup(jpanel_opc_nuevo_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_warnigs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanel_opc_nuevo_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtf_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtf_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtf_nom_prof, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_nom_prof, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtf_nom_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_nom_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanel_opc_nuevo_grupoLayout.setVerticalGroup(
            jpanel_opc_nuevo_grupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_opc_nuevo_grupoLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lbl_nom_grupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_nom_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_nom_prof)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_nom_prof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_materia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_warnigs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel4.setText("Nombre:");

        jLabel5.setText("Boleta");

        jtf_input_boletaalum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_input_boletaalumActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_agregar_alumnosLayout = new javax.swing.GroupLayout(panel_agregar_alumnos);
        panel_agregar_alumnos.setLayout(panel_agregar_alumnosLayout);
        panel_agregar_alumnosLayout.setHorizontalGroup(
            panel_agregar_alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_agregar_alumnosLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_input_nomalum, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_input_boletaalum, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        panel_agregar_alumnosLayout.setVerticalGroup(
            panel_agregar_alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_agregar_alumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_agregar_alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_input_nomalum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_input_boletaalum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jpanel_claseLayout = new javax.swing.GroupLayout(jpanel_clase);
        jpanel_clase.setLayout(jpanel_claseLayout);
        jpanel_claseLayout.setHorizontalGroup(
            jpanel_claseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_claseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jpanel_claseLayout.setVerticalGroup(
            jpanel_claseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_claseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jLabel6.setText("Nombre:");

        jLabel7.setText("Boleta");

        jtf_input_asistencia_boletaalum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_input_asistencia_boletaalumActionPerformed(evt);
            }
        });

        btn_tomar_asistencia_alum.setText("Agregar Asistencia");
        btn_tomar_asistencia_alum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tomar_asistencia_alumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_tomar_asistencia_alumnoLayout = new javax.swing.GroupLayout(panel_tomar_asistencia_alumno);
        panel_tomar_asistencia_alumno.setLayout(panel_tomar_asistencia_alumnoLayout);
        panel_tomar_asistencia_alumnoLayout.setHorizontalGroup(
            panel_tomar_asistencia_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tomar_asistencia_alumnoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_input_asistencia_nomalum_, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_input_asistencia_boletaalum, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_tomar_asistencia_alum, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        panel_tomar_asistencia_alumnoLayout.setVerticalGroup(
            panel_tomar_asistencia_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tomar_asistencia_alumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_tomar_asistencia_alumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_input_asistencia_nomalum_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_input_asistencia_boletaalum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tomar_asistencia_alum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Guarda_Hora_inicial_de_clase.setText("jLabel8");

        javax.swing.GroupLayout Panel_PrincipalLayout = new javax.swing.GroupLayout(Panel_Principal);
        Panel_Principal.setLayout(Panel_PrincipalLayout);
        Panel_PrincipalLayout.setHorizontalGroup(
            Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_tomar_asistencia_alumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                        .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_agregar_alumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpanel_clase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpanel_opc_nuevo_grupo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpanel_opc_buscar_grupo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_conenedor_superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_contenedor_botones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Guarda_Hora_inicial_de_clase, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Panel_PrincipalLayout.setVerticalGroup(
            Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_conenedor_superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_contenedor_botones, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpanel_opc_buscar_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpanel_opc_nuevo_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_agregar_alumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpanel_clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_tomar_asistencia_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Guarda_Hora_inicial_de_clase)
                .addContainerGap(1528, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void select_gruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_gruposActionPerformed
          // TODO add your handling code here:
          jpanel_clase.setVisible(false);
        panel_tomar_asistencia_alumno.setVisible(false);
        jpanel_opc_nuevo_grupo.setVisible(false);
        panel_agregar_alumnos.setVisible(false);
        jpanel_opc_buscar_grupo.setVisible(true);
        JOptionPane.showMessageDialog(rootPane, "nomas a ver si la tabla jala o nel");
        
        if( !(select_grupos.getSelectedItem().equals("Seleccionar grupo"))){
            
            MostrarAlumnos((String)  select_grupos.getSelectedItem());
 
            
        } else {
            ReiniciarTabla();
        }
        
    }//GEN-LAST:event_select_gruposActionPerformed

    private void btn_crear_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crear_grupoActionPerformed

        grupos grup = new  grupos();
       if(jtf_nom_grupo.getText().equals("") || jtf_nom_prof.getText().equals("") || jtf_ciclo.getText().equals("") || jtf_materia.getText().equals("")){
            
            lbl_warnigs.setText("Introducir datos");
            
        } else if (grup.Verificar_duplicado(jtf_nom_grupo.getText())) {
            
            lbl_warnigs.setText("Grupo ya registrado");
           
       } else {
           grup.Crear_grupo(jtf_nom_prof.getText(), jtf_materia.getText(), jtf_nom_grupo.getText(), jtf_ciclo.getText());
       //  grup.Crear_grupo(nom_prof, nom_mat, nom_grupo, ciclo);
        }




        // TODO add your handling code here:
    }//GEN-LAST:event_btn_crear_grupoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        switch (jComboBox1.getSelectedIndex()) {
            case 1:
                panel_agregar_alumnos.setVisible(true);
                break;
            case 2:
                
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jtf_input_boletaalumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_input_boletaalumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_input_boletaalumActionPerformed

    private void btn_nuevo_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevo_grupoActionPerformed
        // TODO add your handling code here:
        jpanel_clase.setVisible(false);
        panel_tomar_asistencia_alumno.setVisible(false);        
        jpanel_opc_nuevo_grupo.setVisible(true);
        jpanel_opc_buscar_grupo.setVisible(false);
        btn_crear_grupo.setVisible(true);
        btn_actualizar_grupo.setVisible(false);
        jtf_nom_grupo.setEnabled(true);
        panel_agregar_alumnos.setVisible(false);
        vaciar_campos();
        
        
        
    }//GEN-LAST:event_btn_nuevo_grupoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Alumno alum = new Alumno();
        alum.Registrar_Alum(jtf_input_nomalum.getText(), jtf_input_boletaalum.getText(), (String) select_grupos.getSelectedItem());
        MostrarAlumnos((String) select_grupos.getSelectedItem());
        jtf_input_nomalum.setText("");
        jtf_input_boletaalum.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_editar_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar_grupoActionPerformed
        // TODO add your handling code here:
        jpanel_opc_buscar_grupo.setVisible(false);
        jpanel_opc_nuevo_grupo.setVisible(true);
        panel_agregar_alumnos.setVisible(false);
        btn_crear_grupo.setVisible(false);
        btn_actualizar_grupo.setVisible(true);
        jtf_nom_grupo.setText(select_grupos.getSelectedItem().toString());
        jtf_nom_prof.setText( grupos.obtenerNombreProfesor( select_grupos.getSelectedItem().toString()) );
        jtf_ciclo.setText( grupos.obtenerNombreCiclo(select_grupos.getSelectedItem().toString()) );
        jtf_materia.setText( grupos.obtenerNombreMateria(select_grupos.getSelectedItem().toString()) );
        jtf_nom_grupo.setEnabled(false);
        
     
    }//GEN-LAST:event_btn_editar_grupoActionPerformed

    private void btn_actualizar_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_grupoActionPerformed
        // TODO add your handling code here:
        
        grupos.modificarCiclo(jtf_ciclo.getText(), select_grupos.getSelectedItem().toString());
        grupos.modificarProfesor(jtf_nom_prof.getText(), select_grupos.getSelectedItem().toString());
        grupos.modificarMateria(jtf_materia.getText(), select_grupos.getSelectedItem().toString());        

        
    }//GEN-LAST:event_btn_actualizar_grupoActionPerformed

    private void btn_inicar_claseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicar_claseActionPerformed
        // TODO add your handling code here:
        
        String hora_inicio_clase = JOptionPane.showInputDialog("Introduzca la hora de inicio de la clase");
        Guarda_Hora_inicial_de_clase.setText(hora);
        
        jpanel_clase.setVisible(true);
        panel_tomar_asistencia_alumno.setVisible(true);
        ///no visible
        jpanel_opc_buscar_grupo.setVisible(false);
        jpanel_opc_nuevo_grupo.setVisible(false);
        panel_agregar_alumnos.setVisible(false);
        btn_crear_grupo.setVisible(false);
        btn_actualizar_grupo.setVisible(false);
        
        
        
        asistencia asis = new asistencia();
        asis.Registrar_Clase(lbl_fecha.getText(), hora_inicio_clase);
                
        
        
        
    }//GEN-LAST:event_btn_inicar_claseActionPerformed

    private void jtf_input_asistencia_boletaalumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_input_asistencia_boletaalumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_input_asistencia_boletaalumActionPerformed

    private void btn_tomar_asistencia_alumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tomar_asistencia_alumActionPerformed
        // TODO add your handling code here:
        int id_clase = asistencia.obtenerIdClase(lbl_fecha.getText(), Guarda_Hora_inicial_de_clase.getText());
        asistencia nasis = new asistencia();
        nasis.Registrar_Asistencia( select_grupos.getSelectedItem().toString(), jtf_input_asistencia_nomalum_.getText(), jtf_input_asistencia_boletaalum.getText() , lbl_fecha.getText() , Guarda_Hora_inicial_de_clase.getText()  ,lbl_hora.getText()  );
        
        
       
       
        
    }//GEN-LAST:event_btn_tomar_asistencia_alumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz_principal().setVisible(true);
            }
        });
    }
    
    public void ObtenerGrupos(){
         List<String> elementos = new ArrayList<>();
         conecction cone = new conecction();
         elementos.add("Seleccionar grupo");
         try (Connection  con =  cone.ConectarBD() ) {
            String consulta = "SELECT nom_grupo  FROM grupo ";
            try (PreparedStatement statement = con.prepareStatement(consulta)) {
                try (ResultSet resultSet = statement.executeQuery()) {
                    while (resultSet.next()) {
                        String valor = resultSet.getString("nom_grupo");
                        elementos.add(valor);
                    }
                }
            }
        } catch (SQLException e) {
             System.out.println("e");
        }
         
         
       
         
         String[] opciones = elementos.toArray(String[]::new);
         DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>(opciones);
         select_grupos.setModel(modelo);
         
        
        
    
    
    
    }
    
    
    public void MostrarAlumnos(String nom_grupo){
          conecction cone = new conecction();
          DefaultTableModel modeloTabla = new DefaultTableModel();
          
          try (Connection con = cone.ConectarBD()) {
            String consulta = "SELECT nom_alum, boleta_alum FROM alumno WHERE id_grupo = ?";
            try (PreparedStatement statement = con.prepareStatement(consulta)) {
                statement.setInt(1,grupos.obtenerIdGrupo(nom_grupo) );
                try (ResultSet resultSet = statement.executeQuery()) {
                    // Configurar las columnas de la JTable
                    modeloTabla.addColumn("Nombre del Alumno");
                    modeloTabla.addColumn("Boleta del Alumno");

                    // Agregar filas a modeloTabla
                    while (resultSet.next()) {
                        Object[] fila = {
                                resultSet.getString("nom_alum"),
                                resultSet.getString("boleta_alum")
                        };
                        modeloTabla.addRow(fila);
                    }
                }
            }
        } catch (SQLException e) {
              System.out.println(e);
        }

        // Establecer el modelo de la JTable
        jtabla_datos_grupos.setModel(modeloTabla);
      
        
    }
    
    public void ReiniciarTabla(){
        DefaultTableModel modelvacio = new DefaultTableModel();
        modelvacio.addColumn("Nombre alumno");
        modelvacio.addColumn("Boleta alumno");
        jtabla_datos_grupos.setModel(modelvacio);
        
    }
    
    void vaciar_campos(){
        
        jtf_materia.setText("");
        jtf_ciclo.setText("");
        jtf_nom_grupo.setText("");
        jtf_nom_prof.setText("");
    
    
    }
    
      void mostrarFecha(){
		
		Date date = new Date();
		DateFormat dateFormat=new SimpleDateFormat("dd/MM/yy");
	    
            lbl_fecha.setText(dateFormat.format(date));
	
	}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Guarda_Hora_inicial_de_clase;
    private javax.swing.JPanel Panel_Principal;
    private javax.swing.JPanel Panel_boton_ayudante;
    private javax.swing.JPanel Panel_etiqueta_FECHA;
    private javax.swing.JPanel Panel_etiqueta_HORA;
    private javax.swing.JButton bnt_importar_datos;
    private javax.swing.JButton bnt_mod_ayud;
    private javax.swing.JButton btn_actualizar_grupo;
    private javax.swing.JButton btn_crear_grupo;
    private javax.swing.JButton btn_editar_grupo;
    private javax.swing.JButton btn_elimimnar_grupo;
    private javax.swing.JButton btn_inicar_clase;
    private javax.swing.JButton btn_nuevo_grupo;
    private javax.swing.JButton btn_tomar_asistencia_alum;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jbl_set_nom_Materia;
    private javax.swing.JLabel jbl_set_nom_gupo;
    private javax.swing.JLabel jbl_set_nom_prof;
    private javax.swing.JLabel jlb_grupo_seleccionado;
    private javax.swing.JPanel jpanel_clase;
    private javax.swing.JPanel jpanel_opc_buscar_grupo;
    private javax.swing.JPanel jpanel_opc_nuevo_grupo;
    private javax.swing.JTable jtabla_datos_grupos;
    private javax.swing.JTextField jtf_ciclo;
    private javax.swing.JTextField jtf_input_asistencia_boletaalum;
    private javax.swing.JTextField jtf_input_asistencia_nomalum_;
    private javax.swing.JTextField jtf_input_boletaalum;
    private javax.swing.JTextField jtf_input_nomalum;
    private javax.swing.JTextField jtf_materia;
    private javax.swing.JTextField jtf_nom_grupo;
    private javax.swing.JTextField jtf_nom_prof;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_hora;
    private javax.swing.JLabel lbl_materia;
    private javax.swing.JLabel lbl_nom_grupo;
    private javax.swing.JLabel lbl_nom_prof;
    private javax.swing.JLabel lbl_warnigs;
    private javax.swing.JPanel panel_agregar_alumnos;
    private javax.swing.JPanel panel_conenedor_superior;
    private javax.swing.JPanel panel_contenedor_botones;
    private javax.swing.JPanel panel_tomar_asistencia_alumno;
    private javax.swing.JComboBox<String> select_grupos;
    private javax.swing.JButton tbn_generar_archivo;
    // End of variables declaration//GEN-END:variables

    @Override
  
    public void run() {
        Thread ct= Thread.currentThread();
        
            while(ct==h1){
                calcula();
                lbl_hora.setText(hora+":"+minutos+":"+segundos+" "+ampm);
                try{
                    Thread.sleep(1000);
                } catch(InterruptedException e){}
            
            }
    
    }

    private void calcula() {
        Calendar calendario = new GregorianCalendar ();
        Date fechaHoraActual = new Date ();
        
        calendario.setTime(fechaHoraActual);
        ampm= calendario.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";
        
        if(ampm.equals("PM")){
            int h=calendario.get(Calendar.HOUR_OF_DAY)-12;
            hora = h>9?""+h:"0"+h;
        }
        else{
             hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }
}
